### ISSUE TITLE
tempai -> tempai

### ISSUE THREAD

**Issue by djuretic** [livewing/mahjong-calc#252]
First of all, thanks a lot for creating this tool, it is very useful!

There is a small typo, "tempai" should be written as "tenpai":

![bildo](https://user-images.githubusercontent.com/1175986/185631493-9643be29-9220-43f6-a05e-dc46ac7fa65d.png)

For example, here "tenpai" is used: https://riichi.wiki/Tenpai

**Comment by livewing** [comment]
"Tempai" is not a typo.

Two types of Japanese romanization are widely used: the Traditional Hepburn and the Modified Hepburn. In the Traditional Hepburn, the consonant b, m, and p are preceded by the syllable n with m[^1].

[^1]: https://en.wikipedia.org/wiki/Hepburn_romanization

**Comment by djuretic** [comment]
Thanks for answering! I'll close this PR.
