### ISSUE TITLE
I'd like to add a Korean translation.

### ISSUE THREAD

**Issue by 24802** [livewing/mahjong-calc#273]
I can't PR because I'm not good at coding and IDE. Could you add it manually?

[ko.yml.txt](https://github.com/livewing/mahjong-calc/files/9809556/ko.yml.txt)

**Comment by 24802** [comment]
Edited.

[ko.yml.txt](https://github.com/livewing/mahjong-calc/files/9809573/ko.yml.txt)

**Comment by livewing** [comment]
Thank you for your contribution!

PR is convenient for reviewing, so I recommend creating a PR. Don’t worry, it can be completed only with a web browser. Follow these steps:

1. Fork this repository
2. Navigate to `locales` directory in your fork
3. Click `Add file` → `Create new file`
4. Name the file `ko.yml`
5. Paste the content of yml file to the text area
6. Click `Commit new file` button
7. Open PR from `Contribute` button in your fork

If you have any problems, please tell me your name and e-mail address. I'll commit the translation with your information.
