### ISSUE TITLE
"After a Kan" does not count in the score calculation

### ISSUE THREAD

**Issue by rishubil** [livewing/mahjong-calc#315]
Even if I enable the "After a Kan" button, it doesn't show up in the list of calculated yakus.

**Comment by obinox** [comment]
"After a Kan" requires the opponent to have 4 of the same card, so if you are holding a winning tile, "After a Kan" does not work.

**Comment by rishubil** [comment]
When I first opened this issue, I thought there was a problem, but after trying again now, it seems to be working fine.

There might still be an issue when using "After a Kan" after a nuki dora in 3-player Mahjong,
but as mentioned in issue #314, I think I can refer to the contents of the 'Change in score' section.
